export default [
    { keywords: ["vue", "vue.js", "vuejs", "nuxt", "nuxt.js", "nuxtjs"], points: 20, reason: "Vue" },
    { keywords: ["laravel"], points: 20, reason: "Laravel" },
    { keywords: ["php"], points: 15, reason: "PHP" },
    { keywords: ["node", "node.js", "nodejs"], points: 10, reason: "Node" },
    { keywords: ["typescript", "ts"], points: 8, reason: "TypeScript" },
    { keywords: ["javascript", "js"], points: 8, reason: "JavaScript" },
    { keywords: ["remote", "remoto", "home office", "teletrabajo"], points: 20, reason: "Remote" },
    { keywords: ["qa", "quality assurance"], points: 15, reason: "QA" },
    { keywords: ["selenium"], points: 15, reason: "Selenium" },
    { keywords: ["cypress"], points: 10, reason: "Cypress" },
    { keywords: ["solution", "solutions engineer"], points: 15, reason: "Solutions Engineer" },
    { keywords: ["consult", "consulting", "consultoria", "consultoría"], points: 10, reason: "Consulting" },
    { keywords: ["documentation", "documentacion", "documentación"], points: 15, reason: "Documentation" },
    { keywords: ["technical writer", "tech writer"], points: 20, reason: "Technical Writer" },
    { keywords: ["senior", "sr", "sr."], points: 5, reason: "Senior" },
];